image: "dothanhtrung/bevy-dev:latest"

before_script:
  - sed -i '/^target-dir =/d' .cargo/config.toml

cache: &global_cache
  key: cargo_cache
  paths:
    - target/
    - .cargo/registry/index
    - .cargo/registry/cache
    - .cargo/bin
  policy: pull-push

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  SQLX_OFFLINE: true

check:
  stage: build
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo check
    - /usr/local/cargo/bin/cargo-sweep sweep -t 60 || true
  rules:
    - changes:
        - Cargo.toml
        - src/**/*
        - examples/**/*
        - tests/**/*

release_build:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --release
    - mkdir -p output/sddm/res && cp target/release/sdmm output/sddm/ && cp -r res/html output/sddm/res/ && cp -r res/css output/sddm/res/
  rules:
    - if: '$CI_COMMIT_TAG'   # Only run on tag
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"
    paths:
      - output/sdmm
